import { useState } from 'react'
import jsPDF from 'jspdf'
import { useIncidentContext } from '../hooks/useIncidentContext'

const SEV_COLOR = {
  Critical: 'text-red-400 bg-red-400/10 border-red-400/30',
  High:     'text-orange-400 bg-orange-400/10 border-orange-400/30',
  Medium:   'text-yellow-400 bg-yellow-400/10 border-yellow-400/30',
  Low:      'text-green-400 bg-green-400/10 border-green-400/30',
}

function Section({ icon, title, color, children }) {
  return (
    <div className="flex flex-col gap-2">
      <span className={`text-xs font-bold uppercase tracking-widest font-mono ${color}`}>{icon} {title}</span>
      {children}
    </div>
  )
}

export default function AIIncidentReport({ result }) {
  const [report, setReport]       = useState(null)
  const [loading, setLoading]     = useState(false)
  const [generated, setGenerated] = useState(false)
  const buildContext = useIncidentContext(result)

  if (!result) return null

  const generate = async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/incident-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ context: buildContext() })
      })
      const data = await res.json()
      const clean = data.report.replace(/```json|```/g, '').trim()
      setReport(JSON.parse(clean))
      setGenerated(true)
    } catch (e) {
      console.error('Report error:', e)
    } finally {
      setLoading(false)
    }
  }

  const downloadPDF = () => {
    const doc = new jsPDF()
    const pw = doc.internal.pageSize.getWidth()
    let y = 20

    const addSection = (title, content) => {
      if (y > 260) { doc.addPage(); y = 20 }
      doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.setTextColor(40, 40, 40)
      doc.text(title, 14, y); y += 6
      doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(80, 80, 80)
      const lines = doc.splitTextToSize(content, pw - 28)
      doc.text(lines, 14, y); y += lines.length * 5 + 8
    }

    const addList = (title, items) => {
      if (y > 260) { doc.addPage(); y = 20 }
      doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.setTextColor(40, 40, 40)
      doc.text(title, 14, y); y += 6
      doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(80, 80, 80)
      items.forEach(item => {
        const lines = doc.splitTextToSize(`• ${item}`, pw - 28)
        doc.text(lines, 14, y); y += lines.length * 5 + 2
      })
      y += 4
    }

    doc.setFontSize(18); doc.setFont('helvetica', 'bold'); doc.setTextColor(20, 20, 20)
    doc.text(report.title, 14, y); y += 10
    doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(120, 120, 120)
    doc.text(`Date: ${report.date}  |  Severity: ${report.severity}`, 14, y); y += 12
    doc.setDrawColor(200, 200, 200); doc.line(14, y, pw - 14, y); y += 8

    addSection('Summary', report.summary)
    addSection('Root Cause', report.rootCause)
    if (report.timeline?.length > 0) addList('Timeline', report.timeline.map(t => `${t.time} — ${t.event}`))
    addSection('Fix Applied', report.fixApplied)
    if (report.lessonsLearned?.length > 0) addList('Lessons Learned', report.lessonsLearned)
    if (report.preventionSteps?.length > 0) addList('Prevention Steps', report.preventionSteps)

    doc.setFontSize(8); doc.setTextColor(150, 150, 150)
    doc.text('Generated by LogWise AI — Powered by Splunk MCP', 14, 285)
    doc.save(`incident-report-${Date.now()}.pdf`)
  }

  return (
    <div className="result-card border-l-2 border-l-rose-400">
      <div className="card-header">
        <div className="w-6 h-6 rounded-md flex items-center justify-center bg-rose-400/10 text-rose-400">
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        </div>
        <span className="card-label text-rose-400">AI Incident Report</span>
        {generated && <span className="ml-auto text-xs px-2 py-0.5 rounded-full font-mono font-bold bg-rose-400/10 text-rose-400 border border-rose-400/30">GENERATED</span>}
      </div>

      <div className="p-4">
        {!generated ? (
          <div className="flex flex-col items-center gap-3 py-2">
            <p className="text-xs font-mono text-center" style={{ color: 'var(--text3)' }}>
              Generate a professional post-incident report<br />with root cause, timeline, fixes & lessons learned
            </p>
            <button onClick={generate} disabled={loading}
              className="flex items-center gap-2 bg-rose-400 hover:opacity-85 disabled:opacity-40 text-white px-4 py-2 rounded-lg text-xs font-semibold transition-opacity">
              {loading
                ? <><span className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" />Generating report...</>
                : <><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>Generate Incident Report</>
              }
            </button>
          </div>
        ) : report && (
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
              <h3 className="text-sm font-bold" style={{ color: 'var(--text)' }}>{report.title}</h3>
              <div className="flex items-center gap-3 text-xs font-mono" style={{ color: 'var(--text3)' }}>
                <span>📅 {report.date}</span>
                <span className={`px-2 py-0.5 rounded-full border font-bold ${SEV_COLOR[report.severity] || SEV_COLOR.Medium}`}>{report.severity}</span>
              </div>
            </div>

            <div style={{ borderTop: '1px solid var(--border)' }} />

            <Section icon="📋" title="Summary" color="text-blue-400">
              <p className="text-xs leading-relaxed" style={{ color: 'var(--text2)' }}>{report.summary}</p>
            </Section>
            <Section icon="🔍" title="Root Cause" color="text-red-400">
              <p className="text-xs leading-relaxed" style={{ color: 'var(--text2)' }}>{report.rootCause}</p>
            </Section>
            {report.timeline?.length > 0 && (
              <Section icon="⏱" title="Timeline" color="text-orange-400">
                <div className="flex flex-col gap-1.5">
                  {report.timeline.map((item, i) => (
                    <div key={i} className="flex gap-2 text-xs">
                      <span className="text-orange-400 font-mono shrink-0 font-bold">{item.time}</span>
                      <span style={{ color: 'var(--text2)' }}>{item.event}</span>
                    </div>
                  ))}
                </div>
              </Section>
            )}
            <Section icon="🔧" title="Fix Applied" color="text-green-400">
              <p className="text-xs leading-relaxed" style={{ color: 'var(--text2)' }}>{report.fixApplied}</p>
            </Section>
            {report.lessonsLearned?.length > 0 && (
              <Section icon="💡" title="Lessons Learned" color="text-yellow-400">
                <div className="flex flex-col gap-1.5">
                  {report.lessonsLearned.map((l, i) => (
                    <div key={i} className="flex gap-2 text-xs">
                      <span className="text-yellow-400 shrink-0">→</span>
                      <span style={{ color: 'var(--text2)' }}>{l}</span>
                    </div>
                  ))}
                </div>
              </Section>
            )}
            {report.preventionSteps?.length > 0 && (
              <Section icon="🛡" title="Prevention Steps" color="text-teal-400">
                <div className="flex flex-col gap-1.5">
                  {report.preventionSteps.map((s, i) => (
                    <div key={i} className="flex gap-2 text-xs">
                      <span className="text-teal-400 font-mono shrink-0 font-bold">{i + 1}.</span>
                      <span style={{ color: 'var(--text2)' }}>{s}</span>
                    </div>
                  ))}
                </div>
              </Section>
            )}

            <div style={{ borderTop: '1px solid var(--border)', paddingTop: '0.75rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <button onClick={downloadPDF}
                className="flex items-center justify-center gap-2 w-full bg-rose-400/10 hover:bg-rose-400/20 border border-rose-400/30 text-rose-400 px-4 py-2 rounded-lg text-xs font-semibold transition-all font-mono">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Download PDF Report
              </button>
              <button onClick={() => { setGenerated(false); setReport(null) }}
                className="text-xs font-mono text-center transition-colors"
                style={{ color: 'var(--text3)' }}>
                ↺ Regenerate
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
